### ISSUE TITLE
m3u8 stream is loaded but ts file not downloading

### ISSUE THREAD

**Issue by ctfrench** [puemos/hls-downloader-web-extension#104]
I've been using HLS downloader to save streams several times per day over the past month, but a couple days ago it stopped working. I can still load an m3u8 stream (normal behavior, loading from 0% to 100% over the course of a couple minutes). However, once that reaches 100%, the HLS Downloader is no longer proceeding to download the ts file.

**Comment by puemos** [comment]
Hey! Thanks for opening the issue, if it's possible, please share a link so I would be able to debug it.

**Comment by ctfrench** [comment]
https://player.arsenal.com/video/liverpool-h-1st-half-1



https://cf.vod.mp.streamamg.com/vod/_definst_/s3/3000504/20191021/3000/0_6u97ymlv_0_zse41y6l_2.mp4/chunklist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZi52b2QubXAuc3RyZWFtYW1nLmNvbS92b2QvX2RlZmluc3RfL3MzLzMwMDA1MDQvMjAxOTEwMjEvMzAwMC8wXzZ1OTd5bWx2XzBfenNlNDF5NmxfMi5tcDQvY2h1bmtsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1OTE1ODQ4ODF9fX1dfQ__&Signature=Ro7ivZaXakR3em9XyrdVs18KYZJO2ljRfyjkmhi9iIWAwz2k~7DTvqGBHIZTvWbS6POxnf5FCTZQWQ~Swy~g~uCLfNNxDYa7L0rUe0XNOXe8MGi~fMDZMsLEd17zw~21YY9ErtS8suWp3-DT-JbSHt2X2h8mOLdZ~D3NcpN~ZwnfTSGEV-0~JI74OgEGrsSIVKIq44BK7cigMBdLnnumyg4JI-yOllIaslEy1quJr8elztqrQZyW6PDvZRAbry0IopfDUBf3Ph6pjHSzCq9q4Tv2Bq2HyOKYi7XcIyL6Dx8kLQhUpZ8ZSO1VaN7Ny8MUktQKnPIXNhNLZBPVOhiQqA__&Key-Pair-Id=APKAJVKZD2WR75FL2ZUQ

**Comment by ctfrench** [comment]
It's working now --- very odd! I'll reach out again if it stops working.

**Comment by ctfrench** [comment]
Also thank you for building this, I use it frequently. Amazing, and very convenient.

**Comment by AnonimousAngel** [comment]
sorry but  loading from 0% to 100% over the course of a couple minutes). However, once that reaches 100%, the HLS Downloader is no longer proceeding to download the ts file

**Comment by ctfrench** [comment]
@puemos I have figured out that this only happens for ts files larger than ~1.75 GB

**Comment by CrazyOlli** [comment]
@puemos I've the same problem. Downloading a ~1.92 Gig TS File works. 1.99 Gig did not work.
Can u please fix it?

**Comment by puemos** [comment]
Work in progress #132
