### ISSUE TITLE
Download either freezes or is stuck at 99% (chrome add on)

### ISSUE THREAD

**Issue by cngc9510** [puemos/hls-downloader-web-extension#108]
Hello, I started using this great chrome extension a few days ago and so far it has been working without any problems. Downloads were quick after all. However, earlier today, the download I was doing at the moment (like, the 6th one I think) froze before it was completed (it spent minutes without progressing) and I was forced to reset it. It eventually worked the next time, but the next thing I wanted to download would later remain stuck at 99% and couldn't progress further despite waiting a few minutes. During the rest of the day, 80 to 90% of download attempts I made were unsuccessfull because of either reason. And I just don't know why this is happening since the extension had worked so well before, even earlier today. I checked on firefox just to be sure and the problem remains there too. Please do something to fix it. I need to get multiple files in a relatively short amount of time. Also, I suggest adding some sort of pause/reset/cancel download so I'm not forced to press "clear" and reload the page all the time.

**Comment by puemos** [comment]
Work in progress #132
