### ISSUE TITLE
why is this extension downloading on TS

### ISSUE THREAD

**Issue by DialexG91** [puemos/hls-downloader-web-extension#110]
MP4 was better

**Comment by 78wesley** [comment]
i would say mkv.

**Comment by candrapersada** [comment]
Downloaded audio and video data is converted to mp4 as it is with the same quality without re-encoding.
This conversion is done inside the extension, without the use of an external server.

**Comment by DialexG91** [comment]
> Downloaded audio and video data is converted to mp4 as it is with the same quality without re-encoding.
> This conversion is done inside the extension, without the use of an external server.

not true, I get the video on .ts file anyway and it's not converted

**Comment by puemos** [comment]
Hello 👋 
@DialexG91 the reason why this extension is downloading TS files is for avoiding the encoding.
In the previous version, the extension just saved the files with .mp4 but they were not mp4 encoded, I prefer to be transparent and until I'm able to perform the encoding keep it TS.

**Comment by shape55** [comment]
Here is the enhancement request for the mp4 conversion feature: https://github.com/puemos/hls-downloader/issues/213.
