### ISSUE TITLE
I download a video from tvthek.orf.at, chrome downloads a resonable time with my maximum network bandwith, but then i cannot find the file

### ISSUE THREAD

**Issue by matmay** [puemos/hls-downloader-web-extension#116]
I download a video from tvthek.orf.at, chrome downloads a resonable time with my maximum network bandwith, but then i cannot find the file

I am using version 2.1.1 in chrome on windows 10

where can i find the downloaded video?

**Comment by puemos** [comment]
Work in progress #132
