### ISSUE TITLE
Why does my download stop before it is finished?

### ISSUE THREAD

**Issue by candrapersada** [puemos/hls-downloader-web-extension#128]
Some browsers may not have the ability to download the required files efficiently. So, For users who commonly encounter intermittent connectivity issues or download failure.
So, add a feature allows the user to automatically resume downloads that have failed.

**Comment by CrazyOlli** [comment]
I've the problem: If a .ts file is larger 2 GB the download stop - testet with newest Chrome and FF on two different Win 10 machines.

**Comment by puemos** [comment]
Work in progress #132
