### ISSUE TITLE
Direct URL Input?

### ISSUE THREAD

**Issue by cdowning22** [puemos/hls-downloader-web-extension#180]
Can it be possible to manually download m3u8 video by simply inputting the url? 
An alternative would be allowing the sniffer to detect video from an extension that allows native playback of m3u8

**Comment by Vangelis66** [comment]
I wholeheartedly second @cdowning22's feature request! :+1: 

The **CWS** contains many _free_ "**VPN**" extensions, actually **HTTPS proxy** extensions, which can only be used within the context of the (Chromium-derived) browser; the "price" a user pays is probably ad insertion, tracking, the need to supply a valid e-mail address etc., but these concerns are OT here... :wink: 

When such an extension is enabled, `hls-downloader` can use the browser's connection settings, i.e. **fetch HLS fragments over said proxy connection** (thus, geo-fenced HLS content can be dumped to disk) :+1: .

Quite often, I might use special URIs and/or apps (outside of `hls-downloader`) to extract **geo-fenced master HLS playlists** (.m3u8), but I **can't use the proxy extension directly** with a third party downloader (youtube-dl/ffmpeg, etc), so if `hls-downloader` could offer the ability to act as an in-browser downloader of a **user supplied .m3u8**, it could be a perfect answer for my usage scenario!

> allowing the sniffer to detect video from an extension that allows native playback of m3u8

Yes, I too use **[Native MPEG-Dash + HLS Playback](https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn)** to watch geo-fenced .m3u8s inside the browser, over a "VPN" extension; sadly, no way to record the stream with `hls-downloader`; I don't know how feasible it would be for a Chrome extension to interact with another Chrome extension, `chrome-extension://*` URIs are special cases...

**Comment by puemos** [comment]
Part of v3.1.0
Download it from here: https://github.com/puemos/hls-downloader-web-extension/releases/tag/v3.1.0
