### ISSUE TITLE
Documentation for Building Extension

### ISSUE THREAD

**Issue by MCDELTAT** [puemos/hls-downloader-web-extension#191]
**Is your feature request related to a problem? Please describe.**
Given that the Firefox extension was removed from the webstore, I wanted to build it myself. I've worked as a Node Developer, so I already had a lot of things set up, but clearly there's very specific configuration needed to build this project. I'd be more than willing to write up the doc (I already was) but I'd need some pointers on how the config is supposed to look.

Currently running:
Node: v14.16.0 -> Linux x86_64. Installed with nvm
Yarn: 1.22.10 Installed with `npm install -g yarn`
Webpack & Webpack-CLI: installed with `yarn global add webpack webpack-cli`

After all of this, running `./build.sh` will report that the react, react-dom, and other packages are not available. I installed these with `yarn add @chakra-ui/core react react-dom react-redux react-router-dom typescript webext-redux webextension-polyfill-ts`

Finally, it gets down to the error:
```
Creating an optimized production build...
Failed to compile.

./src/view/PlaylistsView.tsx
Cannot find module: '@hls-downloader/core/lib/adapters/redux/slices'. Make sure this package is installed.
```
So I'm not sure where the issue is. What sort of config is required to build this?

**Describe the solution you'd like**
Some informal pointers on how this is configured, or even the CI/CD config.

**Additional context**
None.

**Comment by puemos** [comment]
Makes total sense, I'll write something

**Comment by puemos** [comment]
From now on, every release will build and upload the ready to use build
https://github.com/puemos/hls-downloader-web-extension/releases/tag/v3.1.0

Enjoy :)
