### ISSUE TITLE
Google has pulled the ext, can you instead put it on F-droid?

### ISSUE THREAD

**Issue by Jake-s16** [puemos/hls-downloader-web-extension#198]
Google has pulled the ext, can you instead put it on F-droid?

This way, those of us who are unfamiliar with building ext from source, can still install and use this extension.

**Comment by codingwithshawnyt** [comment]
Either that or giving instructions on how to pack the source in to a .crx file and add it would be very useful to the non-dev users.

**Comment by Vangelis66** [comment]
Most thankully, the extension has been archived by `crx4chrome.com`: 

https://www.crx4chrome.com/crx/95140/

where the **latest** and **previous** versions can be obtained (as signed **.CRX** files) and installed 
(open **chrome://extensions**, optionally enable **dev mode**, drag and drop the CRX file) ; of course, not a solution for **future** versions, if/when released by the author...

**Comment by puemos** [comment]
During this weekend I will work on adding a crx to the latest release, and will keep maintaining it for future releases

**Comment by codingwithshawnyt** [comment]
Ok, thanks!

**Comment by puemos** [comment]
Done and automated from now on
https://github.com/puemos/hls-downloader-web-extension/releases/tag/v3.1.0

**Comment by codingwithshawnyt** [comment]
Thanks a bunch!
