### ISSUE TITLE
The package is invalid: "CRX_REQUIRED_PROOF_MISSING".

### ISSUE THREAD

**Issue by rodrigolupatini** [puemos/hls-downloader-web-extension#201]
First, congratulations for your effort and dedication. I have been following the extension for a long time and it has already helped me a lot in my work.

Let's get to the point. After dragging the .CRX file into the Chrome extensions page and clicking Continue (in the message about extensions can damage), an error appears: The package is invalid: "CRX_REQUIRED_PROOF_MISSING".
![1](https://user-images.githubusercontent.com/86860596/124338699-678fca80-db77-11eb-9808-0fedfff7d319.png)
![2](https://user-images.githubusercontent.com/86860596/124338704-6b235180-db77-11eb-80e7-04bd179fe8c3.png)

**Comment by puemos** [comment]
Thanks, I'll try to solve it, meanwhile, you can achieve the same with the zip file

**Comment by rodrigolupatini** [comment]
ok, i will try. thanks for the feedback.
