### ISSUE TITLE
Nothing here on lookmovie

### ISSUE THREAD

**Issue by BazzaBlogz** [puemos/hls-downloader-web-extension#25]
If I use VideoDownloadHelper it can find the hls and download it however hls extension can not see it in the sniffer. This is on lookmovie.ag . Here is the link to the movie: https://lookmovie.ag/movies/view/wonder-woman-2017 although it happens on movie i go on and here is the m3u8 link from videodownloadhelper: https://fe13.lookmovie.ag/b3Z4lAY0_0jm1TYTgc8GhQ/1561907441/storage2/movies/wonder-woman-2017/1080p/index.m3u8 . I would download using VideoDownloadHelper but for some reason the movies always come out with stutters and skipped frame which I think I saw is an encoding issue but I'm not sure.

**Comment by puemos** [comment]
https://lookmovie.ag is down
