### ISSUE TITLE
"Failed - Network error" with NHK videos

### ISSUE THREAD

**Issue by soljarka** [puemos/hls-downloader-web-extension#60]
I'm trying to download an NHK video, for example:
[https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2058461/](https://www3.nhk.or.jp/nhkworld/en/ondemand/video/2058461/)

I select the bandwidth;
The download tab appears with blue progress percent number;
The progress reaches 100%;
A file appears in chrome downloads with an error "Failed - Network error".

My chrome version: 79.0.3945.130

**Comment by puemos** [comment]
@soljarka Now it works!
