### ISSUE TITLE
0% download

### ISSUE THREAD

**Issue by Vailman** [puemos/hls-downloader-web-extension#68]
Hi, download does not work for me... Stream is detected, 3 different resolutions, but download doesn't progress... Can you help me please ?

**Comment by puemos** [comment]
Hey! are you able to share a link?

**Comment by Vailman** [comment]
Of course! Any video on this website : https://mixwiththemasters.com/

**Comment by bahman1361** [comment]
Same problem here with the videos in https://khonyagar.com/

**Comment by puemos** [comment]
@Vailman Unfortunately, it's not a bug, the extension is not able to fetch secured playlists and videos #4, that of course, for privacy reasons.
@bahman1361 the videos are using a custom mechanism of m3u8 encrypting (they are not providing the iv in the m3u8 playlist which makes it impossible to decrypt the chunk automatically)
