### ISSUE TITLE
Download starts, completes but will not save to computer

### ISSUE THREAD

**Issue by ste182** [puemos/hls-downloader-web-extension#69]
Hi

Using the downloader to download a video, the downloader detects video, downloads to 100% over the correct length of time(video is around 5gb's and takes around 30mins to get to 100%), however when i click on the download button nothing happens.

**Comment by CodeSmith32** [comment]
I'm having the same issue, but for a much smaller video (20mins). Download finishes, but nothing happens other than that the download button becomes disabled and I can't download other resolutions.

Afterward, it also breaks, and won't detect any other streams until I restart the browser.

**Browser:** Torch Browser
**URL:** https://www.ted.com/talks/bill_gates_innovating_to_zero

**Comment by puemos** [comment]
Work in progress #132
