### ISSUE TITLE
HDD overload after 100% of download

### ISSUE THREAD

**Issue by frkotou** [puemos/hls-downloader-web-extension#74]
The disk is completely overloaded at 100% download status.

**Comment by puemos** [comment]
Hey! can you share a link?

**Comment by frkotou** [comment]
What link? This happens with all videos.

**Comment by frkotou** [comment]
What link? This happens with all videos.

**Comment by puemos** [comment]
Can you please share your:
- OS
- Chrome version

Thanks!

**Comment by frkotou** [comment]
It also happens on Firefox. I have Windows 8.1.
Chrome: 81.0.4044.122
Firefox: 75.0

Unfortunately, I can't say the version of the plugin in which this didn't happen. Today I received an update for the plugin in black color. The previous version in white color worked quickly and well.

**Comment by puemos** [comment]
All right, I will investigate, thanks for opening the bug 💪

**Comment by frkotou** [comment]
Thanks. I would like to add a note that the disk is so overloaded that it is necessary to restart the computer.

**Comment by puemos** [comment]
@frkotou can you please try again with Firefox, v2.1.1?

**Comment by frkotou** [comment]
No changes.

**Comment by puemos** [comment]
Do you experience the problem on the following site:
https://hls-js.netlify.app/demo/

**Comment by frkotou** [comment]
The video on this site works fine.

**Comment by puemos** [comment]
so can you share a link to a stream that triggers the issue?

**Comment by frkotou** [comment]
Yes, but I don't know if works for you. It's from some service for Czech Republic.

https://ttc-cdn3-pub.mtv.cdn.moderntv.eu/moderntv/stream/kino_barrandov/0-20-hls/storage.m3u8?_cdn_attrs=account%3Dmoderntv%2Cresource%3Dkino_barrandov_stream_ez&_cdn_session=22308293965&_cdn_timestamp=1588259193&duration=9600&start=1587723000&_cdn_token=95f837b7c55409282c09b9cac050d7786212c15c

**Comment by puemos** [comment]
Work in progress #132
