### ISSUE TITLE
Overview of currently downloading streams

### ISSUE THREAD

**Issue by randombyte-developer** [puemos/hls-downloader-web-extension#75]
After the recent update the overview page where all active downloads are listed is gone. You have to click on a detected stream and then see that it is actually downloading. Maybe the download progress can be added to the detected streams?

![image](https://user-images.githubusercontent.com/10366256/80228479-66980a80-864f-11ea-82bd-54d020dc1dc1.png)

**Comment by puemos** [comment]
I will add an additional page for all the active downloads

**Comment by puemos** [comment]
Released on v2.1.0 "Pending review on the stores (Chrome/Firefox)"
