### ISSUE TITLE
Add a "Clear all streams" button

### ISSUE THREAD

**Issue by randombyte-developer** [puemos/hls-downloader-web-extension#76]
I would suggest to add a "Clear all streams" button. And a button for each stream? Something like this:

![image](https://user-images.githubusercontent.com/10366256/80229793-36ea0200-8651-11ea-98eb-4d517c9b6e8e.png)

**Comment by puemos** [comment]
Released on v2.1.0 "Pending review on the stores (Chrome/Firefox)"

**Comment by puemos** [comment]
FYI: @randombyte-developer chrome just released v2.1.1

**Comment by randombyte-developer** [comment]
Thanks for the quick implementation :)
