### ISSUE TITLE
ts files no longer converted to mp4

### ISSUE THREAD

**Issue by dskrad** [puemos/hls-downloader-web-extension#77]
Prior to version 2.0, *.m3u8 playlist files were converted to mp4. Now the m3u8 is saved as *.ts

I prefer mp4 file format.

**Comment by puemos** [comment]
Hey! nothing changed except for the file extension, in the future I may introduce mp4 encoding

**Comment by dskrad** [comment]
Ok, I understand. I remember an older version used ts extension, then recently it was changed to mp4 extension. Can you default back to the mp4 extension? Even if the underlying file is the same?

Also, separate issue, the downloads tab is now gone. Can we get that back?

**Comment by shape55** [comment]
Here is the enhancement request for this feature to be added: https://github.com/puemos/hls-downloader/issues/213.
