### ISSUE TITLE
New Version - Large Files don't download 

### ISSUE THREAD

**Issue by DARKDAN** [puemos/hls-downloader-web-extension#79]
After the new update, it is impossible to download large files - or live records over 2 hours. It did this without problems on a 24h channel by downloading tracks of 4h and 3.5GB. Now it's impossible, I had to change programs.

before the maximum problem that occurred was to have to restart the extension (I believe to release buffer, something like that) - but it was downloaded perfectly.

the new version is impossible. I got 100% but NO DONWLOAD anymore. 

Short files is ok. awsome as usual.

Anyway, tks for this great project! :D

**Comment by puemos** [comment]
Thank you for opening this issue, in version 2.1.1 I changed the system to use Blobs instead of UInt8Arrays, we will have to wait for our friends in google to finish the review, and then you will be able to test it.

**Comment by puemos** [comment]
OR you can try with Firefox https://addons.mozilla.org/en-US/firefox/addon/hls-downloader/

**Comment by DARKDAN** [comment]
Hi - tks for the fast reply - 

I test now with firefox - and the same issue. I got 100% but no file is download. (for a big file 3.5GB and 4hrs of stream).

small files it's ok.  

Old version sometimes I got this problem - even with small files - but - I just restart the extension - and it's perfect again. Now - even restarting - no file is downloaded.   :(

best regards!

**Comment by puemos** [comment]
I'll try to use `Filesystem API` but it will take a while to code.

**Comment by DARKDAN** [comment]
no problem. I can wait. This is the best extension of all.
I test here and I got more minor bugs (just restart and it's ok again)
- I cannot download the same stream with other resolution (Already identified) 
- I cannot download the same "reloaded" stream (with the issue above I try to reload, but now the extension doesn't identified nothing) - either if I change the stream to another stream and get back. I need to close the tab.

= I test this to try to download the big stream in a small resolution - 720p fails - and I will try as 360p. I can't. I need to close the tab and restart. Then I got the download with Dialog Window.
In the old version it was easier, it was possible to download several streams, and go browsing in the same window without this issue. all streams were catched.

tks and best regards!

**Comment by DARKDAN** [comment]
sorry -  I said that I got the 360p with Dialog Window - but no. That's another issue.

For 720p the dialog window doesn't open
For 360p the dialog window OPEN - I "save" - but doesn't save. I got a "Blob Recurse" error. 

tks and best regards! :D

**Comment by DARKDAN** [comment]
I test now to download "on demand" programs (not live) - in the same provider - and works very well as usual.  1h episodes with 1GB max.

- Download 3 eps at same time with 720p and max bitrate
- Download the same episode with diferent resolutions without restart (on live I can't do this)

congrats for the great job!
:D

**Comment by puemos** [comment]
Work in progress #132
