### ISSUE TITLE
Install from GitHub in Chrome?

### ISSUE THREAD

**Issue by psonnosp** [puemos/hls-downloader-web-extension#81]
How do I install this in Chrome? Need the new version and don't have the time to wait for Google to add it to the store.
Tried downloading it as a zip and drop it in extensions but get an error that it cant unzip it. Tried 'Load Unpacked' but the only place it finds a manifest it says something is wrong with it.

**Comment by puemos** [comment]
Try following this guide, let me know if it's still not working for you.
https://webkul.com/blog/how-to-install-the-unpacked-extension-in-chrome/

**Comment by psonnosp** [comment]
That guide is for 'Load Unpacked' which I described in my first post didn't work, or am I missing something?

**Comment by puemos** [comment]
1. Download `hls-chrome.zip`

![image](https://user-images.githubusercontent.com/13174025/80284748-9a8f3080-8720-11ea-877f-a6bfae980c7f.png)

2. Extract the zip
![image](https://user-images.githubusercontent.com/13174025/80284782-db874500-8720-11ea-8095-a182ee6e6bd7.png)

3. go to `chrome://extensions/`

4. Click `Load unpacked`
![image](https://user-images.githubusercontent.com/13174025/80284795-f954aa00-8720-11ea-8df2-2f7ccddaafeb.png)

5. Choose the `dist` folder
![image](https://user-images.githubusercontent.com/13174025/80284810-112c2e00-8721-11ea-83c2-6888fa1e52c8.png)

**Comment by psonnosp** [comment]
I know how to install, but where do I find that file?
I downloaded what was on the front page so theres probably why it didn't work...

**Comment by puemos** [comment]
ok ok ok :)
here you can find all the releases: https://github.com/puemos/hls-downloader-web-extension/releases
here is a link to v2.1.1: https://github.com/puemos/hls-downloader-web-extension/releases/download/v2.1.1/hls-chrome.zip

**Comment by psonnosp** [comment]
Thanks 😃

**Comment by psonnosp** [comment]
Still produced an unplayable file though so that was all for nothing...

**Comment by puemos** [comment]
is it possible for you to share a link?

**Comment by psonnosp** [comment]
It's on the paid part of a newspaper so no :/
