### ISSUE TITLE
New Issue doesn't list downloaded and in progress items.

### ISSUE THREAD

**Issue by mohit-thakur-721** [puemos/hls-downloader-web-extension#84]
New Issue doesn't list downloaded and in progress items in a separate tab.
and from the playlist there is no option to stop the unwanted downloads.

**Comment by puemos** [comment]
Release in version 2.1.1, Pending review on Chrome, Ready on Firefox

**Comment by puemos** [comment]
FYI: @mohit-thakur-721 chrome just released v2.1.1
