### ISSUE TITLE
Stuck at 0% due to encryption?

### ISSUE THREAD

**Issue by ogmorelia** [puemos/hls-downloader-web-extension#89]
**Describe the bug**
So, every other site i use extension with operates fine, its this specific site that will load the link, but will remain at 0% after clicking on download button. 

**To Reproduce**
`https://hlsvod-l3c-clt1.media.plus.espn.com/ps01/espn/hls/2018/12/09/9290c1a5-ddfa-4d86-8718-23a2fc940a4e/1544324790269/asset_7000k.m3u8`

 - OS: Windows 10 HE 1903
 - Browser:
Firefox 75.0 (64-bit) & Chrome Version 81.0.4044.129 (Official Build) (64-bit)
 
Thank you!

**Comment by puemos** [comment]
Hey! thanks for opening the issue, unfortunately, it's not a bug, the extension is not able to fetch secured playlists and videos #4, that of course, for privacy reasons.
