### ISSUE TITLE
cancelling option

### ISSUE THREAD

**Issue by insearchofsolitude** [puemos/hls-downloader-web-extension#91]
sometimes when the video has several qualities i accidentally hit the wrong quality, in the "blue themed" version of this extention, i could've easily deleted the download from downloading list, but now in this new version i can't do that and have to either wait till the download is complete or close the browser. 

this isn't a big issue especially when the volume of the file is less than 50 MBs, but sometimes the large files can be troublesome.

**Comment by puemos** [comment]
Will do!
