### ISSUE TITLE
Plugin usage with known playlists

### ISSUE THREAD

**Issue by aedicted** [puemos/hls-downloader-web-extension#97]
Hello,

since the actually for-this-more-suitable-tool "Streamlink" is quite buggy when it comes to random read timeout errors for whatever reason, I'm looking for an alternative which is capable to download segments from m3u8 playlists in multiple threads to increase the effective data throughput and resemble them in one file.

While your tool seems to support URL detection from websites, I wonder how I can use your tool when I already know the m3u8-URL of a specific stream. At least in text form or entered a HREF in an HTML file, it doesn't seem to detect anything ...

**Comment by bolds07** [comment]
this plugin simple doesnt detect the playlist... would be so much simplier to give option to provide the playlist url

**Comment by puemos** [comment]
Part of v3.1.0, due to chrome removal, you will need to install manually, check out here: https://github.com/puemos/hls-downloader-web-extension#installation
