### ISSUE TITLE
Listing for Microsoft Edge (chromium version)

### ISSUE THREAD

**Issue by superusercode** [puemos/hls-downloader-web-extension#98]
**Is your feature request related to a problem? Please describe.**
Make the HLS downloader extension available on the edge addons store. Edge is now based on chromium and no longer requires additional work to convert the extension. Existing users can install straight from the CWS, but this would be more convenient.

**Describe the solution you'd like**
There is no work to port the extensions since the new edge is based on chrome. All users on Windows/macOS (and Linux in the near future) are already able to install it from the chrome web store when prompted to enable downloads from the CWS. The extension submission process is detailed at https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Describe alternatives you've considered**
Using the download chrome extensions feature of edge.

**Comment by puemos** [comment]
It's already on the go, I just need to supply a `Privacy policy URL` which I do not have.

**Comment by superusercode** [comment]
I've seen open source projects just link to a markdown document in their repo as a privacy policy (i.e. https://github.com/KevinRoebert/ClearUrls/blob/master/PRIVACY.md) . Maybe that is a suitable solution?

**Comment by puemos** [comment]
Done, https://microsoftedge.microsoft.com/addons/detail/hls-downloader/ldehhnlpcedapncohebgmghanffggffc
